import {useState,useRef,useEffect} from 'react';
import * as XLSX from 'xlsx';
import {LayoutDashboard,ArrowDownLeft,ArrowUpRight,ArrowLeftRight,Wallet,ChartNoAxesCombined,Info,ChevronRight,ChevronDown,Download,Plus,Search,Menu,X,SlidersHorizontal,TrendingUp,PiggyBank,Home,Utensils,Car,Heart,Film,Zap,Briefcase,Gift,Paintbrush,MoreHorizontal,Check,AlertCircle,Pencil,Trash2} from 'lucide-react';
import {seedTransactions,seedBudgets,incomeCategories,expenseCategories,colors,today,currentMonth,money,total,monthName,dateLabel,budgetState,type Transaction,type Budget,type Kind} from './data';
type Page='Dashboard'|'Income'|'Transactions'|'Budgets'|'Monthly report'|'About us';
const nav=[{name:'Dashboard',icon:LayoutDashboard},{name:'Income',icon:ArrowDownLeft},{name:'Transactions',icon:ArrowLeftRight},{name:'Budgets',icon:Wallet},{name:'Monthly report',icon:ChartNoAxesCombined}] as const;
const catIcons:Record<string,typeof Home>={Food:Utensils,Transport:Car,Housing:Home,Bills:Zap,Health:Heart,Entertainment:Film,Salary:Briefcase,Freelance:Paintbrush,Gift:Gift};
function CategoryIcon({category}:{category:string}){const I=catIcons[category]||Wallet;return <span className="category-icon" style={{color:colors[category]||'#007c70',background:(colors[category]||'#00a795')+'15'}}><I size={18}/></span>}
export default function App(){
 const [page,setPage]=useState<Page>('Dashboard'); const [mobile,setMobile]=useState(false);
 const [transactions,setTransactions]=useState<Transaction[]>(seedTransactions);const [budgets,setBudgets]=useState<Budget[]>(seedBudgets);
 const [month,setMonth]=useState(currentMonth);
 const [query,setQuery]=useState('');const [typeFilter,setTypeFilter]=useState('all');const [categoryFilter,setCategoryFilter]=useState('all');const [logMonth,setLogMonth]=useState(currentMonth);
 const [editing,setEditing]=useState<string|null>(null);const [modal,setModal]=useState<'transaction'|'budget'|'delete'|null>(null);const dialog=useRef<HTMLDialogElement>(null);
 const [draft,setDraft]=useState({type:'income' as Kind,amount:'',category:'Salary',date:today,note:''});const [budgetDraft,setBudgetDraft]=useState({category:'Food',amount:''});
 const [error,setError]=useState('');const [toast,setToast]=useState('');const [deleteId,setDeleteId]=useState('');
 useEffect(()=>{if(modal&&!dialog.current?.open)dialog.current?.showModal();else if(!modal)dialog.current?.close()},[modal]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer)},[toast]);
 const filteredMonth=transactions.filter(t=>t.date.startsWith(month));const income=total(filteredMonth,'income'),expenses=total(filteredMonth,'expense'),savings=Math.round((income-expenses)*100)/100;
 const rate=income?savings/income*100:null;
 const breakdown=expenseCategories.map(category=>({category,spent:total(filteredMonth.filter(t=>t.category===category),'expense'),budget:budgets.find(b=>b.category===category&&b.month===month)?.amount})).sort((a,b)=>b.spent-a.spent);
 const recent=[...filteredMonth].sort((a,b)=>b.date.localeCompare(a.date)||Number(b.id.slice(1))-Number(a.id.slice(1)));
 function navigate(p:Page){setPage(p);setMobile(false);setQuery('');setTypeFilter('all');setCategoryFilter('all');window.scrollTo(0,0)}
 function openTransaction(kind:Kind,t?:Transaction){setEditing(t?.id||null);setDraft(t?{...t,amount:String(t.amount)}:{type:kind,amount:'',category:kind==='income'?'Salary':'Food',date:today,note:''});setError('');setModal('transaction')}
 function saveTransaction(){
  const n=Number(draft.amount),allowed=draft.type==='income'?incomeCategories:expenseCategories;
  if(!/^\d+(\.\d{1,2})?$/.test(draft.amount)||!Number.isFinite(n)||n<=0||n>10000000){setError('Enter an amount greater than zero, up to $10,000,000, with at most two decimal places.');return}
  if(!allowed.includes(draft.category)){setError('Choose a category that matches this transaction type.');return}
  const d=new Date(draft.date+'T12:00:00');if(!/^\d{4}-\d{2}-\d{2}$/.test(draft.date)||Number.isNaN(d.getTime())||d.getFullYear()<1900||d.toISOString().slice(0,10)!==draft.date||draft.date>today){setError('Choose a valid date on or before October 9, 2026.');return}
  if(editing&&!transactions.some(t=>t.id===editing)){setError('Transaction not found. Close this form and try again.');return}
  const record={...draft,amount:Math.round(n*100)/100,id:editing||'t'+Date.now()};setTransactions(ts=>editing?ts.map(t=>t.id===editing?record:t):[...ts,record]);setModal(null);setToast(editing?'Transaction updated. All totals have been recalculated.':'Transaction added. All totals have been recalculated.');
 }
 function openBudget(category:string){setBudgetDraft({category,amount:String(budgets.find(b=>b.category===category&&b.month===month)?.amount||'')});setError('');setModal('budget')}
 function saveBudget(){const n=Number(budgetDraft.amount);if(!expenseCategories.includes(budgetDraft.category)||!/^\d+(\.\d{1,2})?$/.test(budgetDraft.amount)||!Number.isFinite(n)||n<=0||n>10000000){setError('Choose an expense category and enter a positive budget, with at most two decimal places.');return}setBudgets(bs=>[...bs.filter(b=>!(b.month===month&&b.category===budgetDraft.category)),{month,category:budgetDraft.category,amount:n}]);setModal(null);setToast('Monthly budget updated.')}
 function removeTransaction(){if(!transactions.some(t=>t.id===deleteId)){setError('Transaction not found.');return}setTransactions(ts=>ts.filter(t=>t.id!==deleteId));setModal(null);setToast('Transaction deleted. All totals have been recalculated.')}
 const logRows=[...transactions].filter(t=>(page!=='Income'||t.type==='income')&&(!logMonth||t.date.startsWith(logMonth))&&(page==='Income'||typeFilter==='all'||t.type===typeFilter)&&(categoryFilter==='all'||t.category===categoryFilter)&&(!query||(t.note+' '+t.category).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date)||Number(b.id.slice(1))-Number(a.id.slice(1)));
 function exportExcel(){const book=XLSX.utils.book_new();const rows=page==='Income'||page==='Transactions'?logRows:recent;XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(rows.map(t=>({Date:t.date,Type:t.type,Category:t.category,Description:t.note,Amount:t.amount}))),page==='Income'?'Income':'Transactions');if(page!=='Income'&&page!=='Transactions'){XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet([{Month:month,Income:income,Expenses:expenses,Savings:savings,'Savings rate':rate===null?'N/A':rate.toFixed(1)+'%','All-time balance':total(transactions,'income')-total(transactions,'expense')}]),'Summary');XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(breakdown.map(b=>({Category:b.category,Spent:b.spent,Budget:b.budget??'No budget',Status:budgetState(b.spent,b.budget)}))),'Budgets')}XLSX.writeFile(book,`Finora-${page.toLowerCase().replaceAll(' ','-')}-${page==='Income'||page==='Transactions'?logMonth||'all-time':month}.xlsx`);setToast('Your Excel file has been exported.')}
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
  register({name:'read_finora_summary',description:'Read the currently selected month and its calculated totals from this preview.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({month,income,expenses,savings,savingsRate:rate,allTimeBalance:total(transactions,'income')-total(transactions,'expense')})});
  register({name:'navigate_finora',description:'Open a Finora preview page without changing financial data.',inputSchema:{type:'object',properties:{page:{type:'string',enum:['Dashboard','Income','Transactions','Budgets','Monthly report','About us']}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const value=(input as {page?:Page})?.page;if(!value||!['Dashboard','Income','Transactions','Budgets','Monthly report','About us'].includes(value))throw new Error('Choose a valid Finora page.');navigate(value);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return{page:value};}});
  return()=>lifecycle.abort();
 },[month,income,expenses,savings,rate,transactions]);
 function table(rows:Transaction[],actions=false){return rows.length?<div className="table-scroll"><table><thead><tr><th>Transaction</th><th>Category</th><th>Date</th><th className="right">Amount</th>{actions&&<th className="right">Actions</th>}</tr></thead><tbody>{rows.map(t=><tr key={t.id}><td><div className="transaction-name"><CategoryIcon category={t.category}/><span><strong>{t.note||t.category}</strong><small>{t.type==='income'?'Income':'Expense'}</small></span></div></td><td><span className="category-tag">{t.category}</span></td><td className="muted">{dateLabel(t.date)}</td><td className={'right amount '+(t.type==='income'?'positive':'')}>{t.type==='income'?'+':'−'}{money(t.amount)}</td>{actions&&<td className="right"><button className="icon-button" aria-label={'Edit '+(t.note||t.category)} onClick={()=>openTransaction(t.type,t)}><Pencil size={15}/></button><button className="icon-button delete-button" aria-label={'Delete '+(t.note||t.category)} onClick={()=>{setDeleteId(t.id);setError('');setModal('delete')}}><Trash2 size={15}/></button></td>}</tr>)}</tbody></table></div>:<div className="empty"><Search size={30}/><h3>No transactions match</h3><p>Try another month or clear your filters.</p></div>}
 const filters=<div className="filters"><label className="search-box"><Search size={18}/><span className="sr-only">Search transactions</span><input placeholder="Search transactions…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><span className="sr-only">Filter month</span><input type="month" value={logMonth} onChange={e=>setLogMonth(e.target.value)}/></label>{page==='Transactions'&&<label><span className="sr-only">Transaction type</span><select aria-label="Transaction type" value={typeFilter} onChange={e=>{setTypeFilter(e.target.value);setCategoryFilter('all')}}><option value="all">All types</option><option value="income">Income</option><option value="expense">Expense</option></select></label>}<label><span className="sr-only">Category</span><select aria-label="Category" value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="all">All categories</option>{(page==='Income'||typeFilter==='income'?incomeCategories:typeFilter==='expense'?expenseCategories:[...incomeCategories,...expenseCategories]).map(c=><option key={c}>{c}</option>)}</select></label><button className="text-button" onClick={()=>{setQuery('');setTypeFilter('all');setCategoryFilter('all');setLogMonth('')}}>Clear filters</button></div>;
 const budgetTable=<div className="table-scroll"><table><thead><tr><th>Category</th><th>Monthly budget</th><th>Spent</th><th>Remaining / over</th><th>Usage</th><th>Status</th>{page==='Budgets'&&<th>Actions</th>}</tr></thead><tbody>{breakdown.map(b=><tr key={b.category}><td><div className="transaction-name"><CategoryIcon category={b.category}/><strong>{b.category}</strong></div></td><td>{b.budget?money(b.budget):'Not set'}</td><td>{money(b.spent)}</td><td>{b.budget?money(Math.abs(b.budget-b.spent))+(b.spent>b.budget?' over':' left'):'—'}</td><td>{b.budget?(b.spent/b.budget*100).toFixed(1)+'%':'—'}<div className="progress budget-table-progress"><span style={{width:b.budget?Math.min(100,b.spent/b.budget*100)+'%':'0',background:b.spent>(b.budget||Infinity)?'#ca745b':'#009c88'}}/></div></td><td><span className={'status '+(b.budget?(b.spent>b.budget?'exceeded':b.spent>=b.budget*.8?'near':'track'):'')}>{budgetState(b.spent,b.budget)}</span></td>{page==='Budgets'&&<td><button className="text-button inline" onClick={()=>openBudget(b.category)}>{b.budget?'Edit':'Set budget'}</button>{b.budget&&<button className="icon-button delete-button" aria-label={'Remove '+b.category+' budget'} onClick={()=>{setBudgets(bs=>bs.filter(x=>!(x.month===month&&x.category===b.category)));setToast(b.category+' budget removed.')}}><Trash2 size={15}/></button>}</td>}</tr>)}</tbody></table></div>;
 const stats=<div className="stats"><article className="stat"><div className="stat-top"><span>Total income</span><span className="stat-icon green"><ArrowDownLeft size={21}/></span></div><h2>{money(income)}</h2><p><span className="positive">{filteredMonth.filter(t=>t.type==='income').length} income sources</span><span>This month</span></p></article><article className="stat"><div className="stat-top"><span>Total expenses</span><span className="stat-icon blue"><ArrowUpRight size={21}/></span></div><h2>{money(expenses)}</h2><p><span>{filteredMonth.filter(t=>t.type==='expense').length} transactions</span><span>This month</span></p></article><article className="stat saving"><div className="stat-top"><span>Monthly savings</span><span className="stat-icon"><PiggyBank size={22}/></span></div><h2>{money(savings)}</h2><p><span>{rate===null?'Savings rate unavailable':`${rate.toFixed(1)}% savings rate`}</span><span>{savings<0?'Overspent':'Income − expenses'}</span></p></article></div>;
 return <div className="app"><header className="topbar"><a href="#dashboard" className="brand" onClick={e=>{e.preventDefault();navigate('Dashboard')}}><img src="./finora-icon.svg" alt=""/><img className="wordmark" src="./finora-wordmark.svg" alt="Finora"/></a><button className="icon-button mobile-toggle" onClick={()=>setMobile(!mobile)} aria-label="Toggle navigation"><Menu size={23}/></button><nav className="breadcrumbs" aria-label="Breadcrumb"><button onClick={()=>navigate('Dashboard')}><Home size={16}/>Home</button><ChevronRight size={15}/><span>{page}</span></nav><div className="top-right"><span className="demo-pill">Design preview</span><span className="avatar" aria-label="Omar">O</span></div></header>
 {mobile&&<button className="scrim" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
 <aside className={'sidebar '+(mobile?'open':'')}><div className="workspace-label">PERSONAL FINANCE</div><nav aria-label="Main navigation">{nav.map(n=><button className={page===n.name?'active':''} key={n.name} onClick={()=>navigate(n.name)}><n.icon size={20}/>{n.name}{page===n.name&&<span className="nav-indicator"/>}</button>)}</nav><div className="side-bottom"><div className="side-note"><div className="note-symbol"><PiggyBank size={26}/></div><strong>A little clarity.<br/>A lot more possibility.</strong><p>Make room for what matters.</p></div><button className={'about-link '+(page==='About us'?'active':'')} onClick={()=>navigate('About us')}><Info size={19}/>About us</button><div className="profile"><span className="avatar">O</span><div><strong>Omar</strong><small>Personal workspace</small></div><ChevronDown size={16}/></div></div></aside>
 <main><div className="page-heading"><div><div className="eyebrow">YOUR MONEY, CLEARLY</div><h1>{page==='Dashboard'?'A little more in control.':page}</h1><p>{({Dashboard:'Welcome back, Omar. Here’s where you stand this month.',Income:'Every payday, project, and little extra.',Transactions:'Your money in motion. Every detail in one place.',Budgets:'Give every category a little direction.','Monthly report':'Step back. See the whole month.','About us':'A clearer picture. A more confident you.'})[page]}</p></div>{page!=='About us'&&<div className="heading-actions">{page!=='Income'&&page!=='Transactions'&&<label className="month-picker"><span className="sr-only">Selected month</span><input type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/></label>}<button className="button secondary" onClick={exportExcel}><Download size={17}/>Export Excel</button>{(page==='Income'||page==='Transactions')&&<button className="button primary" onClick={()=>openTransaction(page==='Income'?'income':'expense')}><Plus size={17}/>{page==='Income'?'Add income':'Add transaction'}</button>}</div>}</div>
 {page==='Dashboard'&&<>{!filteredMonth.length&&<p className="report-note">No transactions this month. Select another month to explore your activity.</p>}{stats}<div className="balance-strip"><span><Wallet size={18}/>Available balance <small>· All time</small></span><strong>{money(total(transactions,'income')-total(transactions,'expense'))}</strong><span className="balance-note">Every income. Every expense. One clear picture.</span></div>
 <div className="dashboard-grid"><section className="card spending-card"><div className="card-heading"><div><h3>Where your money goes</h3><p>Spending by category · {monthName(month)}</p></div><span className="subtle-icon"><ChartNoAxesCombined size={20}/></span></div><div className="spending-content"><div className="donut-wrap"><div className="donut" style={{background:expenses?`conic-gradient(${breakdown.reduce((a,b,i)=>{const start=breakdown.slice(0,i).reduce((s,x)=>s+x.spent,0)/expenses*100;return [...a,`${colors[b.category]} ${start}% ${start+b.spent/expenses*100}%`]},[] as string[]).join(',')})`:'#edf2f4'}}><div><small>Total spent</small><strong>{money(expenses)}</strong><span>across {breakdown.filter(b=>b.spent).length} categories</span></div></div></div><div className="legend">{breakdown.map(b=><div className="legend-row" key={b.category}><span className="color-dot" style={{background:colors[b.category]}}/><span>{b.category}</span><strong>{money(b.spent)}</strong><small>{expenses?(b.spent/expenses*100).toFixed(1):0}%</small></div>)}</div></div></section>
 <section className="card budget-watch"><div className="card-heading"><div><h3>Keep an eye on</h3><p>Your budget check-in</p></div><span className="alert-icon"><AlertCircle size={19}/></span></div>{breakdown.filter(b=>b.budget&&b.spent>=b.budget*.8).map(b=><div className="watch-item" key={b.category}><div><CategoryIcon category={b.category}/><strong>{b.category}</strong><span className={'status '+(b.spent>b.budget!?'exceeded':'near')}>{budgetState(b.spent,b.budget)}</span></div><div className="progress"><span style={{width:Math.min(100,b.spent/b.budget!*100)+'%',background:b.spent>b.budget!?'#ca745b':'#d3a458'}}/></div><p><span>{money(b.spent)} <small>of {money(b.budget!)}</small></span><strong>{b.spent>b.budget!?money(b.spent-b.budget!)+' over':money(b.budget!-b.spent)+' left'}</strong></p></div>)}{!breakdown.some(b=>b.budget&&b.spent>=b.budget*.8)&&<div className="empty"><Check size={24}/><p>No categories near or over budget.</p></div>}<button className="text-button" onClick={()=>navigate('Budgets')}>View all budgets</button></section></div>
 <section className="card recent-card"><div className="card-heading"><div><h3>Recent activity</h3><p>The latest entries in your money story.</p></div><button className="button light" onClick={()=>navigate('Transactions')}>All transactions</button></div>{table(recent.slice(0,5))}</section></>}
 {page==='Income'&&<><section className="income-overview"><div className="income-total"><span className="eyebrow">MONEY COMING IN</span><h2>{money(total(logRows,'income'))}</h2><p>{logMonth?monthName(logMonth):'All time'} · {logRows.length} matching entries</p><div className="income-line"><span style={{width:'100%'}}/></div><span className="income-caption">A foundation for everything you’re planning.</span></div><div className="income-sources"><div className="card-heading"><h3>Your income sources</h3><span className="muted">{logMonth?monthName(logMonth):'All time'}</span></div>{incomeCategories.map(c=>{const amount=total(logRows.filter(t=>t.category===c),'income');const sum=total(logRows,'income');return <div className="source-item" key={c}><CategoryIcon category={c}/><div><strong>{c}</strong><div className="progress"><span style={{width:(sum?amount/sum*100:0)+'%',background:'#009f8b'}}/></div></div><span><strong>{money(amount)}</strong><small>{sum?(amount/sum*100).toFixed(1):0}% of income</small></span></div>})}</div></section><section className="card log-card"><div className="card-heading"><div><h3>Income log <span className="count">{logRows.length}</span></h3><p>Your earnings, neatly in order.</p></div><span className="log-badge"><ArrowDownLeft size={16}/>Income only</span></div>{filters}{table(logRows,true)}<div className="table-footer"><span>{logRows.length} matching entries</span><strong>Total income <span className="positive">{money(total(logRows,'income'))}</span></strong></div></section></>}
 {page==='Transactions'&&<><div className="transaction-summary"><div><span>Money in</span><strong className="positive">+{money(total(logRows,'income'))}</strong></div><div><span>Money out</span><strong>−{money(total(logRows,'expense'))}</strong></div><div><span>Net change</span><strong>{money(total(logRows,'income')-total(logRows,'expense'))}</strong></div><span className="summary-caption">Based on your current filters</span></div><section className="card log-card"><div className="card-heading"><div><h3>Transaction log <span className="count">{logRows.length}</span></h3><p>Newest first. Nothing left out.</p></div><ArrowLeftRight className="muted" size={21}/></div>{filters}{table(logRows,true)}<div className="table-footer"><span>{logRows.length} matching transactions</span><span>All amounts in USD</span></div></section></>}
 {page==='Budgets'&&<><div className="budget-intro"><div><span className="eyebrow">PLAN WITH PURPOSE</span><h2>{money(budgets.filter(b=>b.month===month).reduce((s,b)=>s+b.amount,0))}</h2><p>Planned across {budgets.filter(b=>b.month===month).length} categories · {monthName(month)}</p></div><div className="budget-key"><span className="status track">On track · under 80%</span><span className="status near">Near limit · 80–100%</span><span className="status exceeded">Exceeded · over 100%</span></div></div><section className="card"><div className="card-heading"><div><h3>Monthly category budgets</h3><p>Unbudgeted spending is still included in your totals.</p></div><button className="button primary" onClick={()=>openBudget('Food')}><Plus size={16}/>Set budget</button></div>{budgetTable}</section></>}
 {page==='Monthly report'&&<>{stats}<div className="report-note"><TrendingUp size={22}/><div><strong>{filteredMonth.length?(savings<0?'This month is overspent.':income?'You kept '+(rate||0).toFixed(1)+'% of your income.':'No income recorded this month.'):'No transactions this month.'}</strong><p>{expenses?`${breakdown[0].category} is your largest spending category at ${money(breakdown[0].spent)} (${(breakdown[0].spent/expenses*100).toFixed(1)}% of spending).`:'Your spending breakdown will appear when an expense is recorded.'}</p></div></div><div className="card report-breakdown"><div className="card-heading"><div><h3>Spending breakdown</h3><p>{monthName(month)}</p></div><span className="muted">{money(expenses)} total</span></div>{breakdown.map(b=><div className="report-bar" key={b.category}><span>{b.category}</span><div className="progress"><span style={{width:(expenses?b.spent/expenses*100:0)+'%',background:colors[b.category]}}/></div><strong>{money(b.spent)}</strong><small>{expenses?(b.spent/expenses*100).toFixed(1):0}%</small></div>)}</div><section className="card recent-card"><div className="card-heading"><h3>Budget comparison</h3></div>{budgetTable}</section></>}
 {page==='About us'&&<section className="card about-card"><img src="./finora-icon.svg" alt="Finora icon"/><span className="eyebrow">MEET FINORA</span><h2>Less guessing.<br/>More understanding.</h2><p>Finora helps you understand where your money goes, make thoughtful spending decisions, and see what’s left for the things you care about.</p><div className="about-values"><div><Wallet size={22}/><h3>Track simply</h3><p>Bring income and everyday spending into one clear view.</p></div><div><PiggyBank size={22}/><h3>Plan deliberately</h3><p>Set monthly limits that reflect your priorities.</p></div><div><ChartNoAxesCombined size={22}/><h3>See your progress</h3><p>Turn daily entries into a meaningful monthly picture.</p></div></div><div className="template-note"><strong>About this preview</strong><p>This interactive template uses fictional data for September and October 2026. Changes stay in memory during this visit and reset when you reload. No bank accounts are connected.</p></div></section>}
 <footer><span>© 2026 Finora</span><span>Sample data · USD · Changes reset on reload</span><button onClick={()=>navigate('About us')}>About us</button></footer></main>
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null)}} aria-labelledby="dialog-title"><div className="dialog-content"><div className="dialog-heading"><div><span className="eyebrow">{modal==='budget'?monthName(month):'YOUR MONEY, CLEARLY'}</span><h2 id="dialog-title">{modal==='transaction'?(editing?'Edit transaction':draft.type==='income'?'Add income':'Add transaction'):modal==='budget'?'Set monthly budget':'Delete transaction?'}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={22}/></button></div>
 {modal==='transaction'&&<form noValidate onSubmit={e=>{e.preventDefault();saveTransaction()}}><div className="segmented"><button type="button" className={draft.type==='income'?'selected':''} onClick={()=>setDraft({...draft,type:'income',category:'Salary'})}><ArrowDownLeft size={17}/>Income</button><button type="button" className={draft.type==='expense'?'selected':''} onClick={()=>setDraft({...draft,type:'expense',category:'Food'})}><ArrowUpRight size={17}/>Expense</button></div><label className="field">Amount (USD)<input autoFocus inputMode="decimal" placeholder="0.00" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><div className="form-grid"><label className="field">Category<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{(draft.type==='income'?incomeCategories:expenseCategories).map(c=><option key={c}>{c}</option>)}</select></label><label className="field">Date<input type="date" max={today} value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label></div><label className="field">Description <span className="muted">(optional)</span><input maxLength={120} placeholder="What was this for?" value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" className="button secondary" onClick={()=>setModal(null)}>Cancel</button><button type="submit" className="button primary">{editing?'Save changes':'Add '+draft.type}</button></div></form>}
 {modal==='budget'&&<form noValidate onSubmit={e=>{e.preventDefault();saveBudget()}}><label className="field">Expense category<select value={budgetDraft.category} onChange={e=>setBudgetDraft({category:e.target.value,amount:String(budgets.find(b=>b.month===month&&b.category===e.target.value)?.amount||'')})}>{expenseCategories.map(c=><option key={c}>{c}</option>)}</select></label><label className="field">Monthly limit (USD)<input inputMode="decimal" value={budgetDraft.amount} onChange={e=>setBudgetDraft({...budgetDraft,amount:e.target.value})} placeholder="0.00"/></label><p className="form-hint">Saving replaces the existing budget for this category and month.</p>{error&&<p role="alert" className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" className="button secondary" onClick={()=>setModal(null)}>Cancel</button><button type="submit" className="button primary">Save budget</button></div></form>}
 {modal==='delete'&&<><p className="delete-copy">This entry will be removed and your totals will be recalculated.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><button className="button secondary" onClick={()=>setModal(null)}>Keep transaction</button><button className="button danger" onClick={removeTransaction}>Delete transaction</button></div></>}
 </div></dialog>{toast&&<div role="status" className="toast"><Check size={18}/>{toast}</div>}</div>
}
